// Regenerates the two lists that have to know what is in images/.
//
//   node tools/gen-images.mjs
//
// Both were hand-maintained, and a manifest nobody regenerates is worse than
// no manifest at all — so this is the only thing that writes them, and a test
// fails the moment either drifts from disk.
//
//   data/images.js   what the page has locally, so the fallback chain can skip
//                    straight to the file that exists instead of probing for
//                    four that do not
//   sw.js MEDIA      what the service worker precaches for offline, local files
//                    plus every hotlink named in data/program.js
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const local = readdirSync(join(root, 'images'))
  .filter((f) => /\.(gif|jpe?g|png|webp)$/i.test(f))
  .sort();

const hotlinks = [...new Set(
  [...readFileSync(join(root, 'data', 'program.js'), 'utf8')
    .matchAll(/image:\s*"(https:\/\/[^"]+)"/g)].map((m) => m[1])
)].sort();

writeFileSync(join(root, 'data', 'images.js'),
`/* GENERATED by tools/gen-images.mjs — do not edit by hand.
 *
 * Which illustrations exist locally. Without this the fallback chain has to
 * ASK for each candidate in turn, so opening the details panel on an exercise
 * with no local picture fired four 404s, and a full pass over the session fired
 * eighteen. Knowing the answer up front costs one small file.
 *
 * Assigns to \`self\` so the same file works in the page and in a worker.
 */
(function (root) {
  "use strict";
  root.IMAGES = [
${local.map((f) => `    "${f}",`).join('\n')}
  ];
})(typeof self !== "undefined" ? self : this);
`);

const swPath = join(root, 'sw.js');
const sw = readFileSync(swPath, 'utf8');
const media = [...local.map((f) => './images/' + f), ...hotlinks];
const block = `var MEDIA = [\n${media.map((u) => `  "${u}",`).join('\n')}\n];`;
const replaced = sw.replace(/var MEDIA = \[[\s\S]*?\n\];/, block);
if (replaced === sw && !sw.includes(block)) throw new Error('could not find MEDIA in sw.js');
writeFileSync(swPath, replaced);

console.log(`images: ${local.length} local, ${hotlinks.length} hotlinked`);
